/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    EasyLogo: typeof import('./src/components/EasyLogo.vue')['default']
    EasyLogoSmall: typeof import('./src/components/EasyLogoSmall.vue')['default']
    GeneratorInput: typeof import('./src/components/GeneratorInput.vue')['default']
    LoginProbe: typeof import('./src/components/LoginProbe.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RegisterProbe: typeof import('./src/components/RegisterProbe.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusPopUp: typeof import('./src/components/StatusPopUp.vue')['default']
  }
}
